version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: "before_test:"
          command: docker ps
      - run:
          name: "before_test: setup db"
          command: docker-compose run web rails db:create db:migrate
      - run:
          name: rubocop test
          command: bundle exec rubocop -c .rubocop.yml
      - run:
          name: rspec test
          command: bundle exec rspec spec
      - run:
          name: docker-compose down
          command: docker-compose down
