version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 10
      - run:
          name: "check_contena"
          command: docker ps
      - run:
          name: "before_test: setup db"
          command: docker-compose run web rails db:create db:migrate RAILS_ENV=test
      - run:
          name: "rubocop test"
          command: docker-compose run web rubocop -c .rubocop.yml
      - run:
          name: "rspec test"
          command: docker-compose run web rspec spec
      - run:
          name: docker-compose down
          command: docker-compose down
