version: '3'
services:
  db:
    image: mysql:latest
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3010:3000"
    depends_on:
      - db
