version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  web:
    build: .
    command: bundle exec foreman start
    volumes:
      - .:/myapp
    depends_on:
      - db
